# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Checkcalculateanduser' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'checkcalculateanduser' do
    @driver.get('http://localhost:3000/')
    sleep 1
    @driver.find_element(:link_text, 'Войти').click
    sleep 1
    @driver.find_element(:link_text, 'Sign up now!').click
    sleep 1
    @driver.find_element(:id, 'user_name').click
    sleep 1
    @driver.find_element(:id, 'user_name').send_keys('test')
    @driver.find_element(:id, 'user_email').click
    sleep 1
    @driver.find_element(:id, 'user_email').send_keys('test@mail.com')
    @driver.find_element(:id, 'user_password').click
    sleep 1
    @driver.find_element(:id, 'user_password').send_keys('1234')
    @driver.find_element(:name, 'commit').click
    sleep 1
    @driver.find_element(:id, 'session_email').click
    @driver.find_element(:id, 'session_email').send_keys('test@mail.com')
    sleep 1
    @driver.find_element(:id, 'session_password').click
    @driver.find_element(:id, 'session_password').send_keys('1234')
    @driver.find_element(:name, 'commit').click
    sleep 1
    @driver.find_element(:link_text, 'Показать всех пользователей').click
    sleep 1
    @driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(2)').click
    sleep 1
    expect(@driver.find_element(:css, 'h1:nth-child(1)').text).to eq('Current login: test')
    @driver.find_element(:link_text, 'Главная').click
    sleep 1
    @driver.find_element(:link_text, 'Калькулятор').click
    sleep 1
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('2')
    @driver.find_element(:id, 'v2').click
    @driver.find_element(:id, 'v2').send_keys('3')
    sleep 1
    @driver.find_element(:name, 'commit').click
    sleep 1
    @driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(1)').click
    @driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(2)').click
    sleep 1
    expect(@driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(1)').text).to eq('1')
    expect(@driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(2)').text).to eq('6')
    @driver.find_element(:link_text, 'Repeat calculation').click
    sleep 1
    @driver.find_element(:link_text, 'Главная').click
    sleep 1
    @driver.find_element(:link_text, 'Выйти').click
    sleep 1
    @driver.find_element(:link_text, 'Войти').click
    sleep 1
    @driver.find_element(:id, 'session_email').click
    sleep 1
    @driver.find_element(:id, 'session_email').send_keys('admin')
    @driver.find_element(:id, 'session_password').click
    @driver.find_element(:id, 'session_password').send_keys('admin')
    sleep 1
    @driver.find_element(:name, 'commit').click
    sleep 1
    @driver.find_element(:link_text, 'Показать всех пользователей').click
    sleep 1
    @driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(6) > a').click
    sleep 1
    @driver.find_element(:css, 'button').click
    sleep 1
    @driver.find_element(:link_text, 'Главная').click
    sleep 1
    @driver.find_element(:link_text, 'Выйти').click
    sleep 1
    @driver.close
  end
end
