# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Checkauto' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'checkauto' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:link_text, 'Калькулятор').click
    sleep 1
    @driver.find_element(:css, 'h1').click
    sleep 1
    expect(@driver.find_element(:css, 'h1').text).to eq('Sign in')
    @driver.close
  end
end
